# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login-page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import socket
from Chat_page import Chat_Dialog

HOST = 'localhost'
PORT = 1234
address = (HOST, PORT)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(449, 306)
        Dialog.setFixedSize(449, 306)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-40, 70, 551, 41))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(250, 150, 113, 22))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 140, 181, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 230, 101, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 230, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(lambda x: self.login(Dialog))
        self.pushButton_2.clicked.connect(os._exit)

    def login(self, Dialog):
        global username
        global client

        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        username = self.lineEdit.text()
        if username:
            try:
                username_header = f"{len(username):<2048}".encode()
                client.connect(address)
                client.sendall(username_header + username.encode())
                data_header = client.recv(2048)
                data = client.recv(int(data_header.decode())).decode()
            except ConnectionError:
                self.label_2.setText('can\'t connect')
                client.close()
                return

            if data=="0": # username is ok
                self.switch_to_chat_ui(Dialog)
            
            elif data=="1":
                self.label_2.setText(f"{username!r} is bad")
                self.lineEdit.clear()
                client.close()

            else:
                self.label_2.setText("unknown error")
                client.close()
                
        else:
            self.label_2.setText("enter your name first!")

    def switch_to_chat_ui(self, Dialog):
        global client, username
        for widget in Dialog.children():
            widget.deleteLater()
        Dialog.hide()
        chat_dialog = QtWidgets.QDialog(Dialog)
        chat_ui = Chat_Dialog()
        chat_ui.setupUi(chat_dialog, client, username)
        chat_dialog.show()







    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">welcome to ChatRoom</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "please enter your name: "))
        self.pushButton.setText(_translate("Dialog", "Enter"))
        self.pushButton_2.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    username = ""
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
